name: Unstable

on:
  push:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.sys.os }}
    strategy:
      matrix:
        sys: 
          - { os: windows-latest, shell: pwsh }
          - { os: ubuntu-latest,  shell: bash }
          - { os: macos-latest,   shell: bash }

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Install Ubuntu Dependencies
      if: ${{ matrix.sys.os == 'ubuntu-latest' }}
      run: sudo apt update && sudo apt install extra-cmake-modules libwayland-dev libxkbcommon-dev wayland-protocols xorg-dev zenity

    - name: Install MacOS Dependencies
      if: ${{ matrix.sys.os == 'macos-latest' }}
      run: brew update && brew install cmake libpng zlib pkg-config

    - name: Configure Ubuntu CMake
      if: ${{ matrix.sys.os == 'ubuntu-latest' }}
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DZIP_RELEASE=1

    - name: Configure Windows CMake
      if: ${{ matrix.sys.os == 'windows-latest' }}
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DZIP_RELEASE=1

    - name: Configure MacOS CMake
      if: ${{ matrix.sys.os == 'macos-latest' }}
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" -DPNG_ARM_NEON=off -DZIP_RELEASE=1

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --parallel 2

    - name: Release
      uses: ncipollo/release-action@a2e71bdd4e7dab70ca26a852f29600c98b33153e
      with:
        name: ${{ github.ref }}
        tag: 'unstable'
        artifacts: build/wrench_*.zip
        allowUpdates: true
        draft: false
        omitBodyDuringUpdate: true
        omitDraftDuringUpdate: true
        omitNameDuringUpdate: true
        omitPrereleaseDuringUpdate: true
        prerelease: true
        replacesArtifacts: false
        skipIfReleaseExists: false
